site_name: Bar Chart Racer
site_description: Animated bar chart races in Python with the bar_chart_racer package
site_author: Wibo van der Sluis
site_url: https://github.com/sofus-nl/bar_chart_racer/wiki
repo_url: https://github.com/sofus-nl/bar_chart_racer
copyright: Copyright @ 2025 Wibo van der Sluis

theme:
  name: material
  favicon: images/favicon.ico
  custom_dir: docs/overrides
  features:
    - tabs

nav:
  - Home: index.md
  - Installation: installation.md
  - What's New: whats_new.md
  - Tutorial: tutorial.md
  - Data Preparation: data_preparation.md
  - Upcoming Features: upcoming.md
  - API Reference: api.md

extra_css:
  - css/style.css

markdown_extensions:
    - admonition
    - toc:
        permalink: True
    - codehilite:
        guess_lang: false
    - pymdownx.superfences

plugins:
    - search
    - macros
    - minify:
        minify_html: false

extra_javascript:
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.plot.ly/plotly-latest.min.js